### ISSUE TITLE
Problem with unicode and python2 on command compilescss.

### ISSUE THREAD

**Issue by hugotacito** [jrief/django-sass-processor#104]
When I run the following command on my project:

python manage.py compilescss -v 3

I get this error:
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/hugo/.virtualenvs/suap/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/Users/hugo/.virtualenvs/suap/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/hugo/.virtualenvs/suap/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/hugo/.virtualenvs/suap/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/Users/hugo/.virtualenvs/suap/lib/python2.7/site-packages/sass_processor/management/commands/compilescss.py", line 158, in handle
    templates = self.find_templates()
  File "/Users/hugo/.virtualenvs/suap/lib/python2.7/site-packages/sass_processor/management/commands/compilescss.py", line 231, in find_templates
    for name in files if not name.startswith('.') and
  File "/Users/hugo/.virtualenvs/suap/lib/python2.7/site-packages/sass_processor/management/commands/compilescss.py", line 231, in <genexpr>
    for name in files if not name.startswith('.') and
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 15: ordinal not in range(128)
```

My project runs on python2 and has a file with an unicode name:
Ex: 'Documento Eletrônico – Otimização do Tamanho dos Documentos.doc'

The exception is thrown when the command tries to read this filename.

**Comment by jrief** [comment]
Could you please find out which of the statements in that line is causing the problem. In my tests, invoking
```
Python 2.7.15 (default, May  2 2018, 00:56:07)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> name=u'Documento Eletrônico – Otimização do Tamanho dos Documentos.doc'
>>> name.startswith('.')
False
```
does not cause any error.

**Comment by hugotacito** [comment]
Hello @jrief thanks for the quick feedback. 

Yeah, I can't reproduce on pure python but I created a fresh new django project and I was able to reproduce it (it is available at https://github.com/hugotacito/sass_processor_error), please remember to use python 2.7. 

In fact the problem happens in the line 229 of the file management/commands/compilescss.py (for root, _, files in os.walk(str(path)):), this happens because the str function convert the path to ascii (in python 2, even using from future unicode_literals) and it raises the exception when they try to use the function startswith later.

**Comment by jrief** [comment]
can we close this?
I'm unsure how to help here.

**Comment by hugotacito** [comment]
Ok closing.
