### ISSUE TITLE
django 1.8?

### ISSUE THREAD

**Issue by Guest007** [jrief/django-sass-processor#11]
Hi
Is this version ready for Django 1.8 or 1.9?
I've got this error:
```
$ ./manage.py compilescss

Traceback (most recent call last):
  File "./manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File "/home/guest007/.virtualenvs/1/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 351, in execute_from_command_line
    utility.execute()
  File "/home/guest007/.virtualenvs/1/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 343, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/guest007/.virtualenvs/1/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/guest007/.virtualenvs/1/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/home/guest007/.virtualenvs/1/local/lib/python2.7/site-packages/sass_processor/management/commands/compilescss.py", line 31, in handle
    templates = self.find_templates()
  File "/home/guest007/.virtualenvs/1/local/lib/python2.7/site-packages/sass_processor/management/commands/compilescss.py", line 42, in find_templates
    for loader in self.get_loaders():
  File "/home/guest007/.virtualenvs/1/local/lib/python2.7/site-packages/sass_processor/management/commands/compilescss.py", line 66, in get_loaders
    from django.template.loader import (find_template_source as finder_func)
ImportError: cannot import name find_template_source
```

**Comment by jrief** [comment]
Sorry, for not having fixed this yet.
Can you please check the 1.8 release notes. Somtimes they only changed the location of the method, then its really easy to find and fix these problems.
Thanks, Jacob

**Comment by Guest007** [comment]
find_template_source deprecated since Django 1.2.7 as I can found.
Django 1.8 has new template loader due to support custom template engines

**Comment by frostbtn** [comment]
I've fixed it by back-porting template walker again from django-compressor.
Pull [request 13](https://github.com/jrief/django-sass-processor/pull/13). 
Or install from [my fork](https://github.com/frostbtn/django-sass-processor):
```
pip uninstall django-sass-processor
pip install https://github.com/frostbtn/django-sass-processor/zipball/master
```

**Comment by Guest007** [comment]
@frostbtn thank you! I'l try. 
For now I'm solved my trouble by using [Tamarabyte's](https://github.com/Tamarabyte/django-sass-processor) fork.

**Comment by jrief** [comment]
@Guest007 can this be closed now?
