### ISSUE TITLE
Windows(Chinese Simple) Install Error UnicodeDecodeError

### ISSUE THREAD

**Issue by RocsSun** [jrief/django-sass-processor#117]
Hi,man!
When I use pip to install `django-compressor`, throw a decoding exception, can you help me solve it.
Environment：

- Windows Chinese Simple
- Python 3.6.8
 
And thank you!

```dos
(Django-1.11.15venv) F:\Project\DjangoPro\YoutobeBlog>pip install django-sass-processor
Collecting django-sass-processor
  Using cached https://files.pythonhosted.org/packages/93/2d/0f50d7414d59131e5365a869c1092996ad3c6b112b6409f5c80576cae101/
django-sass-processor-0.7.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Linga\AppData\Local\Temp\pip-install-qc5z2kwe\django-sass-processor\setup.py", line 9, in <module>
        long_description = fh.read()
    UnicodeDecodeError: 'gbk' codec can't decode byte 0xa6 in position 3271: illegal multibyte sequence

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Linga\AppData\Local\Temp\pip-install-qc5z2kwe\djan
go-sass-processor\
```

**Comment by jrief** [comment]
Please retry with the latest version from GitHub. It seems to be an encoding problem on Windows. Doesn't happen on Linux and MacOS.

**Comment by jinh0park** [comment]
Same issue occurs in Windows based on Korean.

```
>pip install django-sass-processor==0.7.3
Collecting django-sass-processor==0.7.3
  Using cached https://files.pythonhosted.org/packages/b7/ec/ba3dbb86590b6a9e140008da5aa1bfcbb0401ef49bf41ca02dff9c36a272/django-sass-processor-0.7.3.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Public\Documents\ESTsoft\CreatorTemp\pip-install-9k2hm3jr\django-sass-processor\setup.py", line 9, in <module>
        long_description = fh.read()
    UnicodeDecodeError: 'cp949' codec can't decode byte 0xe2 in position 3269: illegal multibyte sequence
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in C:\Users\Public\Documents\ESTsoft\CreatorTemp\pip-install-9k2hm3jr\django-sass-processor\

```

**Comment by jinh0park** [comment]
Oh I resolved this error via installing this from GitHub with pip.

```
>pip install git+https://github.com/jrief/django-sass-processor.git
Collecting git+https://github.com/jrief/django-sass-processor.git
  Cloning https://github.com/jrief/django-sass-processor.git to c:\users\public\documents\estsoft\creatortemp\pip-req-build-ycn_hsa0
  Running command git clone -q https://github.com/jrief/django-sass-processor.git 'C:\Users\Public\Documents\ESTsoft\CreatorTemp\pip-req-build-ycn_hsa0'
Building wheels for collected packages: django-sass-processor
  Building wheel for django-sass-processor (setup.py) ... done
  Stored in directory: C:\Users\Public\Documents\ESTsoft\CreatorTemp\pip-ephem-wheel-cache-f9rg_viy\wheels\14\0f\cf\2f0583e2eac9a0e16450ccbfb96b3b3ac397f8cf7c1f2c3a40
Successfully built django-sass-processor
Installing collected packages: django-sass-processor
Successfully installed django-sass-processor-0.7.3
``` 

However, while I using the `django-sass-processor` with `sass_tags` as follows, still an error occurs which about file encoding.
```
{% load sass_tags %}
    <link href=“{% sass_src ‘scss/style.scss’ %}” rel=“stylesheet” type=“text/css”/>
``` 

```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\helloalgo-dev\lib\wsgiref\handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "C:\ProgramData\Anaconda3\envs\helloalgo-dev\lib\site-packages\django\contrib\staticfiles\handlers.py", line 65, in __call__
    return self.application(environ, start_response)
  File "C:\ProgramData\Anaconda3\envs\helloalgo-dev\lib\site-packages\django\core\handlers\wsgi.py", line 141, in __call__
    response = self.get_response(request)
  File "C:\ProgramData\Anaconda3\envs\helloalgo-dev\lib\site-packages\django\core\handlers\base.py", line 75, in get_response
    response = self._middleware_chain(request)
  File "C:\ProgramData\Anaconda3\envs\helloalgo-dev\lib\site-packages\django\core\handlers\exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "C:\ProgramData\Anaconda3\envs\helloalgo-dev\lib\site-packages\django\core\handlers\exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "C:\ProgramData\Anaconda3\envs\helloalgo-dev\lib\site-packages\django\core\handlers\exception.py", line 125, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "C:\ProgramData\Anaconda3\envs\helloalgo-dev\lib\site-packages\django\views\debug.py", line 94, in technical_500_response
    html = reporter.get_traceback_html()
  File "C:\ProgramData\Anaconda3\envs\helloalgo-dev\lib\site-packages\django\views\debug.py", line 332, in get_traceback_html
    t = DEBUG_ENGINE.from_string(fh.read())
UnicodeDecodeError: 'cp949' codec can't decode byte 0xe2 in position 9735: illegal multibyte sequence
```

I think this may be able to resolved by configuring `sass --watch ~~~` command(for example, `sass --watch -E utf-8 style.scss:style.css`) but I'm not sure...
