### ISSUE TITLE
Error when you run the command "docker-compose up --build -d"

### ISSUE THREAD

**Issue by mina-gaid** [jrief/django-sass-processor#118]
When executing the command `docker-compose up --build -d` I receive the below error.

This seems to be an error in [jrief/django-sass-processor/edit/master/sass_processor/management/commands/compilescss.py ](https://github.com/jrief/django-sass-processor/edit/master/sass_processor/management/commands/compilescss.py)

```
Step 28/34 : RUN ./manage.py compilescss
 ---> Running in 78c90b4f6dac
/usr/local/lib/python3.6/site-packages/shop/admin/product.py:109: UserWarning: 
Your caching backend does not support deletion by key patterns.
Please use 'django-redis-cache', or wait until the product's HTML
snippet cache expires by itself.
  warnings.warn("\n"
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 206, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.6/site-packages/sass_processor/management/commands/compilescss.py", line 8, in <module>
    from compressor.exceptions import TemplateDoesNotExist, TemplateSyntaxError
ModuleNotFoundError: No module named 'compressor'
ERROR: Service 'wsgiapp' failed to build: The command '/bin/sh -c ./manage.py compilescss' returned a non-zero code: 1

```

This can be re-created by running

```
cookiecutter https://github.com/awesto/cookiecutter-django-shop
cd <app>
docker-compose up --build -d
```

**Comment by AndreasBackx** [comment]
You didn't install `django-compressor` as its module is not found.

**Comment by mina-gaid** [comment]
> You didn't install `django-compressor` as its module is not found.

It's installed. See also [this thread](https://github.com/awesto/cookiecutter-django-shop/issues/6) from last week.

I'm not the only one with this issue.

**Comment by AndreasBackx** [comment]
@jrief will probably know more.

**Comment by jrief** [comment]
RTM here: https://github.com/jrief/django-sass-processor#installation
