### ISSUE TITLE
Incompatibility with django-simple-bulma

### ISSUE THREAD

**Issue by gdude2002** [jrief/django-sass-processor#120]
When making use of [django-simple-bulma](https://github.com/jrief/django-sass-processor), the automatic compilation of sass files referred to in templates using the django-sass-processor template tags works flawlessly, regardless of whether `django-simple-bulma` is in use or not.

However, the `python manage.py compilescss` command breaks, with the following - fairly weird - error:

```py
(frontend) [gdude@arch frontend]$ DEBUG=1 python manage.py compilescss
........................................................................................................................................................................Traceback (most recent call last):
  File "manage.py", line 23, in <module>
    main()
  File "manage.py", line 19, in main
    execute_from_command_line(sys.argv)
  File "/home/gdude/.virtualenvs/frontend-1cyhH2HW/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/gdude/.virtualenvs/frontend-1cyhH2HW/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/gdude/.virtualenvs/frontend-1cyhH2HW/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/gdude/.virtualenvs/frontend-1cyhH2HW/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/gdude/.virtualenvs/frontend-1cyhH2HW/lib/python3.7/site-packages/sass_processor/management/commands/compilescss.py", line 157, in handle
    self.parse_source(py_source)
  File "/home/gdude/.virtualenvs/frontend-1cyhH2HW/lib/python3.7/site-packages/sass_processor/management/commands/compilescss.py", line 214, in parse_source
    self.compile_sass(sass_filename, sass_fileurl)
  File "/home/gdude/.virtualenvs/frontend-1cyhH2HW/lib/python3.7/site-packages/sass_processor/management/commands/compilescss.py", line 292, in compile_sass
    content = sass.compile(**compile_kwargs)
  File "/home/gdude/.virtualenvs/frontend-1cyhH2HW/lib/python3.7/site-packages/sass.py", line 689, in compile
    raise IOError('{!r} seems not a file'.format(filename))
OSError: '/home/gdude/.local/share/virtualenvs/frontend-1cyhH2HW/lib/python3.7/site-packages/django_simple_bulma/path' seems not a file
```

The `path` file referenced at the end of the traceback doesn't actually exist.

I'm not sure if this is a problem with django-simple-bulma or django-sass-processor, so I'll be opening this issue on both repos.

https://github.com/python-discord/django-simple-bulma/issues/28

**Comment by jrief** [comment]
That file shall be written by `compilescss`, so I'm wondering why it should be stored inside `site-packages`.
I'm closing this, because without further information I can't help you here.

**Comment by gdude2002** [comment]
Oh hey, thanks for the reply.

Yep, it's confusing me as well, and I don't have a deep knowledge of Django internals so I'm not really sure where to look.

What information do you need, exactly? It's extremely simple to reproduce.
