### ISSUE TITLE
UnicodeDecodeError When trying to Build from Docker

### ISSUE THREAD

**Issue by knightebsuku** [jrief/django-sass-processor#129]
Hi All
During a docker build process, I get a UnicodeError

```
Downloading https://files.pythonhosted.org/packages/b7/ec/ba3dbb86590b6a9e140008da5aa1bfcbb0401ef49bf41ca02dff9c36a272/django-sass-processor-0.7.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-imdo02z9/django-sass-processor/setup.py", line 9, in <module>
        long_description = fh.read()
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 3269: ordinal not in range(128)
```

The build process works for python 2 but not for python 3.
Is there something that I'm missing?

**Comment by ebsuku** [comment]
Managed to correct this issue by installing the locales library
```
apt install locales
```
and setting it
```
RUN locale-gen en_US.UTF-8
```
