### ISSUE TITLE
compilecss leads to ImportError: cannot import name 'six'

### ISSUE THREAD

**Issue by hybridpicker** [jrief/django-sass-processor#134]
After running `python manage.py compilescss` I get this error:

```
$ python manage.py compilescss
Traceback (most recent call last):
  File "manage.py", line 26, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/opt/anaconda3/envs/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/opt/anaconda3/envs/lib/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/anaconda3/envs/lib/python3.6/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/anaconda3/envs/lib/python3.6/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/opt/anaconda3/envs/lib/python3.6/site-packages/sass_processor/management/commands/compilescss.py", line 141, in handle
    self.parser = self.get_parser(engine)
  File "/opt/anaconda3/envs/lib/python3.6/site-packages/sass_processor/management/commands/compilescss.py", line 122, in get_parser
    from compressor.offline.django import DjangoParser
  File "/opt/anaconda3/envs/lib/python3.6/site-packages/compressor/offline/django.py", line 13, in <module>
    from compressor.templatetags.compress import CompressorNode
  File "/opt/anaconda3/envs/lib/python3.6/site-packages/compressor/templatetags/compress.py", line 3, in <module>
    from django.utils import six
ImportError: cannot import name 'six'
```

Python: 3.6
Django: 3.0.2

**Comment by jrief** [comment]
as you can read from your own stacktrack, this Exception is related to django-compressor, rather than django-sass-processor. Upgrading to django-compressor-2.4 probably helps.
