### ISSUE TITLE
import statement in SCSS file not working with v1.0.1

### ISSUE THREAD

**Issue by iankameron** [jrief/django-sass-processor#154]
When attempting to update to v1.0.1 (or v1.0.0):

Found the following works with v 0.8.2 when running compilecss, but not v1.0.0 or v1.0.1

command: `python billboard/manage.py compilescss`

resulting error states that it can't find 
`>> @import "../../../../node_modules/bootstrap/scss/bootstrap"`

but the only import like it in my SCSS is:
`@import "../../../../node_modules/bootstrap/scss/bootstrap-reboot";`

So it would appear that something around importing is failing.

Other notes:
- `node_modules/bootstrap/scss/bootstrap` is also a SCSS file, so should be OK anyway.
- also seeing the same error in browser on a django error screen when running "manage.py runserver" and trying to access any URL locally. (so it doesn't seem to be just pre-compile related)
- Other versions: django-compressor 2.4.0 ,Django 3.1.8, python 3.6, MacOS 11.2.2, 

I have also tried the following with no success
- pointing to a different scss file like `node_modules/bootstrap/scss/bootstrap` or changing the depth of `../` in the path, but it is not helping. (in any case, it works if I just revert back to the old version without changing anything, so I don't think the import statement is wrong, unless it was wrong before and now something has been fixed in this library making my wrong statement break.)
- adjusting django-compressor versions.

Error details:
```
Traceback (most recent call last):
  File "billboard/manage.py", line 8, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/ian/dev/billboard/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/Users/ian/dev/billboard/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/ian/dev/billboard/env/lib/python3.6/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/ian/dev/billboard/env/lib/python3.6/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/Users/ian/dev/billboard/env/lib/python3.6/site-packages/sass_processor/management/commands/compilescss.py", line 162, in handle
    self.parse_template(template_name)
  File "/Users/ian/dev/billboard/env/lib/python3.6/site-packages/sass_processor/management/commands/compilescss.py", line 275, in parse_template
    self.compile_sass(sass_filename, node.path)
  File "/Users/ian/dev/billboard/env/lib/python3.6/site-packages/sass_processor/management/commands/compilescss.py", line 290, in compile_sass
    content = sass.compile(**compile_kwargs)
  File "/Users/ian/dev/billboard/env/lib/python3.6/site-packages/sass.py", line 738, in compile
    raise CompileError(v)
sass.CompileError: Error: File to import not found or unreadable: ../../../../node_modules/bootstrap/scss/bootstrap.
        on line 174:1 of billboard/static/scss/makeleaps_dev.scss
>> @import "../../../../node_modules/bootstrap/scss/bootstrap"
   ^

Fatal error: local() encountered an error (return code 1) while executing 'python billboard/manage.py compilescss'

Aborting.
```

**Comment by jrief** [comment]
In my projects, I usually add to my `settings.py`

```python
SASS_PROCESSOR_INCLUDE_DIRS = [
    os.path.join(BASE_DIR, os.path.pardir, 'node_modules'),
]
```

This tells the sass-compiler where to look for includes.
