### ISSUE TITLE
TypeError when using Google backend from django-storages

### ISSUE THREAD

**Issue by kdeggelman** [jrief/django-sass-processor#161]
I have
```py
SASS_PROCESSOR_STORAGE = "storages.backends.gcloud.GoogleCloudStorage"
```
and when I run
```
python manage.py compilescss --use-storage
```
I get
```
[28/Jan/2022 12:13:42] ERROR Caught exception in command: compilescss --use-storage
Traceback (most recent call last):
  File "/Users/kdeggelman/dev/projects/enterprise/prospect/manage.py", line 27, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/kdeggelman/.pyenv/versions/prospect/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/Users/kdeggelman/.pyenv/versions/prospect/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/kdeggelman/.pyenv/versions/prospect/lib/python3.7/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/kdeggelman/.pyenv/versions/prospect/lib/python3.7/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/Users/kdeggelman/.pyenv/versions/prospect/lib/python3.7/site-packages/sass_processor/management/commands/compilescss.py", line 168, in handle
    self.parse_template(template_name)
  File "/Users/kdeggelman/.pyenv/versions/prospect/lib/python3.7/site-packages/sass_processor/management/commands/compilescss.py", line 296, in parse_template
    self.compile_sass(sass_filename, node.path)
  File "/Users/kdeggelman/.pyenv/versions/prospect/lib/python3.7/site-packages/sass_processor/management/commands/compilescss.py", line 312, in compile_sass
    self.save_to_destination(content, sass_filename, sass_fileurl)
  File "/Users/kdeggelman/.pyenv/versions/prospect/lib/python3.7/site-packages/sass_processor/management/commands/compilescss.py", line 343, in save_to_destination
    self.storage.save(destpath, ContentFile(content))
  File "/Users/kdeggelman/.pyenv/versions/prospect/lib/python3.7/site-packages/django/core/files/storage.py", line 52, in save
    return self._save(name, content)
  File "/Users/kdeggelman/.pyenv/versions/prospect/lib/python3.7/site-packages/storages/backends/gcloud.py", line 174, in _save
    file_object.blob.upload_from_file(content, rewind=True, size=content.size, **upload_params)
  File "/Users/kdeggelman/.pyenv/versions/prospect/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 1157, in upload_from_file
    client, file_obj, content_type, size, num_retries, predefined_acl
  File "/Users/kdeggelman/.pyenv/versions/prospect/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 1063, in _do_upload
    client, stream, content_type, size, num_retries, predefined_acl
  File "/Users/kdeggelman/.pyenv/versions/prospect/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 857, in _do_multipart_upload
    response = upload.transmit(transport, data, object_metadata, content_type)
  File "/Users/kdeggelman/.pyenv/versions/prospect/lib/python3.7/site-packages/google/resumable_media/requests/upload.py", line 137, in transmit
    data, metadata, content_type
  File "/Users/kdeggelman/.pyenv/versions/prospect/lib/python3.7/site-packages/google/resumable_media/_upload.py", line 292, in _prepare_request
    raise TypeError(u"`data` must be bytes, received", type(data))
TypeError: ('`data` must be bytes, received', <class 'str'>)
```

If I change [this line](https://github.com/jrief/django-sass-processor/blob/3a1293b5c96e9cfff6858fc0b525b731be7aeb3a/sass_processor/management/commands/compilescss.py#L322) from `self.storage.save(destpath, ContentFile(content))` to `self.storage.save(destpath, ContentFile(force_bytes(content)))` then everything works correctly.

I'd be happy to submit a PR, but I don't know what impact that change might have on other storage backends.

**Comment by kdeggelman** [comment]
Looks like this is an issue with `django-storages` and not with `django-sass-processor`. See https://github.com/jschneier/django-storages/issues/708

Sorry for the false alarm
