### ISSUE TITLE
django 1.9 support

### ISSUE THREAD

**Issue by mjonker-embed** [jrief/django-sass-processor#18]
```
python manage.py compilescss
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/django/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/django/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 342, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/django/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 195, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/django/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 39, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/django/venv/local/lib/python2.7/site-packages/sass_processor/management/commands/compilescss.py", line 9, in <module>
    from django.utils.importlib import import_module
ImportError: No module named importlib
```

See http://stackoverflow.com/questions/29931979/recommended-practice-for-using-import-module-in-django-1-8 as well

**Comment by mjonker-embed** [comment]
Fixing that results is a different error:
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/django/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/django/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 342, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/django/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/django/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/django/venv/local/lib/python2.7/site-packages/sass_processor/management/commands/compilescss.py", line 58, in handle
    templates = self.find_templates()
  File "/django/venv/local/lib/python2.7/site-packages/sass_processor/management/commands/compilescss.py", line 93, in find_templates
    for root, _, files in os.walk(path):
  File "/django/venv/lib/python2.7/os.py", line 278, in walk
    names = listdir(top)
TypeError: coercing to Unicode: need string or buffer, Origin found
```

**Comment by jrief** [comment]
Would you mind fixing this?
We can drop support for all versions of Django < 1.7

**Comment by mjonker-embed** [comment]
Willing to look into that, however I don't feel like testing them all. 

Do you have a direction for the last error?

**Comment by mjonker-embed** [comment]
PR is up

**Comment by jrief** [comment]
I'd be happy if I could migrate my own projects to at least Django-1.8. I'm still stuck with 1.7.

**Comment by mjonker-embed** [comment]
I can test 1.8.7 (last 1.8 release)

**Comment by mjonker-embed** [comment]
(perhaps adding tests is an idea with some CI?)

**Comment by mjonker-embed** [comment]
1.8.7 tested, works

**Comment by jrief** [comment]
yes that's something I typically do – see my other projects, here unfortunately I was too lazy ;(

... didn't expect it being wildly used.

**Comment by mjonker-embed** [comment]
Well, I fell in love with SASS and this just works lovely with it.
