### ISSUE TITLE
python manage.py compilescss => ImportError: No module named utils

### ISSUE THREAD

**Issue by teone** [jrief/django-sass-processor#25]
I'm trying to install this preprocessor, I followed the steps in the README and when running `python manage.py compilescss` it throw this error:

```
root@8d6966117fec:/opt/xos# python manage.py compilescss
Traceback (most recent call last):
  File "manage.py", line 25, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/sass_processor/management/commands/compilescss.py", line 57, in handle
    self.parser = self.get_parser(options['engine'])
  File "/usr/local/lib/python2.7/dist-packages/sass_processor/management/commands/compilescss.py", line 74, in get_parser
    from compressor.offline.django import DjangoParser
  File "/usr/local/lib/python2.7/dist-packages/compressor/offline/django.py", line 13, in <module>
    from compressor.templatetags.compress import CompressorNode
  File "/usr/local/lib/python2.7/dist-packages/compressor/templatetags/compress.py", line 5, in <module>
    from compressor.cache import (cache_get, cache_set, get_offline_hexdigest,
  File "/usr/local/lib/python2.7/dist-packages/compressor/cache.py", line 13, in <module>
    from compressor.conf import settings
  File "/usr/local/lib/python2.7/dist-packages/compressor/conf.py", line 5, in <module>
    from django.template.utils import InvalidTemplateEngineError
ImportError: No module named utils
```

While if I add:
```
{% load sass_tags %}
<link rel="stylesheet" type="text/css" href="{% sass_src "xos.scss" %}" />
```

It Throw Error 500 (with no hint also in the console)

Any hint to solve?

I'm running Django 1.7

**Comment by jrief** [comment]
looking at the stacktrace, it seems as if you're using a version of django-compressor which is not compatible with Django-1.7

This btw. is an unrelated question regarding django-sass-processor. It you should not be ask in this issue tracker.

**Comment by bevedoni** [comment]
what should I do if I am using django 1.7? upgrade or downgrade?

**Comment by jrief** [comment]
1. this is not a django-sass-processor problem, but a django-compressor one
2. In Django the file ``django/template/util.py`` has been renamed to ``django/template/utils.py``
therefore look for a version of django-compressor which is compatible with your version of Django.
