### ISSUE TITLE
django.template.base.TemplateDoesNotExist: test

### ISSUE THREAD

**Issue by drivard** [jrief/django-sass-processor#4]
Hi, 

I need help to understand why I cannot compile the scss for production environment.

	Django==1.7.7
	django-sass-processor==0.2.2
	django-compressor==1.5

when trying to run the command line :
	
        python manage.py compilescss
	
I am getting this error:
	

	Traceback (most recent call last):
	  File "manage.py", line 10, in <module>
	    execute_from_command_line(sys.argv)
	  File "~/virtualenvs/blog/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
	    utility.execute()
	  File "~/virtualenvs/blog/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
	    self.fetch_command(subcommand).run_from_argv(self.argv)
	  File "~/virtualenvs/blog/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
	    self.execute(*args, **options.__dict__)
	  File "~/virtualenvs/blog/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
	    output = self.handle(*args, **options)
	  File "~/virtualenvs/blog/lib/python2.7/site-packages/sass_processor/management/commands/compilescss.py", line 28, in handle
	    templates = self.find_templates()
	  File "~/virtualenvs/blog/lib/python2.7/site-packages/sass_processor/management/commands/compilescss.py", line 39, in find_templates
	    for loader in self.get_loaders():
	  File "~/virtualenvs/blog/lib/python2.7/site-packages/sass_processor/management/commands/compilescss.py", line 68, in get_loaders
	    finder_func('test')
	  File "~/virtualenvs/blog/lib/python2.7/site-packages/django/template/loader.py", line 136, in find_template
	    raise TemplateDoesNotExist(name)
	django.template.base.TemplateDoesNotExist: test
	
	
When looking at the code, it pass by the line 61 of ```compilescss.py```

	from django.template.loader import (
	                    find_template as finder_func)
						
and then it fails at line 68 of the same file which is in a try catch

			try:
                # Force Django to calculate template_source_loaders from
                # TEMPLATE_LOADERS settings, by asking to find a dummy template
                finder_func('test')
            except TemplateDoesNotExist:
                pass
				
Can you help me figure out why this is happening?

My settings are:

	in INSTALLED_APPS
	'sass_processor',
	'compressor',
	
	STATICFILES_FINDERS = (
	    'django.contrib.staticfiles.finders.FileSystemFinder',
	    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
	    'compressor.finders.CompressorFinder',
	    'sass_processor.finders.CssFinder',
	)

	COMPRESS_PRECOMPILERS = (
	    ('text/x-scss', 'django_libsass.SassCompiler'),
	)

	COMPRESS_ENABLED = False
	COMPRESS_OFFLINE = True
	SASS_PROCESSOR_ENABLED = True
	SASS_PROCESSOR_ROOT = STATIC_ROOT + '/sass'
	

	TEMPLATE_LOADERS = (
	    'django.template.loaders.filesystem.Loader',
	    'django.template.loaders.app_directories.Loader',
	)

I even tried to set SASS_PROCESSOR_ENABLED = False which didn't change anything.

Regards
Dominick

**Comment by jrief** [comment]
``./manage.py compilescss `` iterates over all templates in your project and recursively searches for templates. You probably reference ``test`` somewhere without having it.

``COMPRESS_PRECOMPILERS`` is not required with **django-sass-processor**.

**Comment by drivard** [comment]
I look all around, in the HTML, in the PY files. I don't have a test template. Plus it is in the code of the command line that it is saying searching for a test dummy template to figure out the loaders.

    # Force Django to calculate template_source_loaders from
    # TEMPLATE_LOADERS settings, by asking to find a dummy template
    finder_func('test')

I will try against an empty app to see how it reacts.

any other ideas?
Thanks

**Comment by drivard** [comment]
I did a small experiment, by adding in my templates/ folder a test.html which didn't work.
Then Itried to create templates/test and then it worked it pass the find_func('test') but then it fails at 

	traceback (most recent call last):
	  File "manage.py", line 10, in <module>
	    execute_from_command_line(sys.argv)
	  File "~/apps/virtualenvs/blog/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
	    utility.execute()
	  File "~/apps/virtualenvs/blog/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
	    self.fetch_command(subcommand).run_from_argv(self.argv)
	  File "~/apps/virtualenvs/blog/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
	    self.execute(*args, **options.__dict__)
	  File "~/apps/virtualenvs/blog/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
	    output = self.handle(*args, **options)
	  File "~/apps/virtualenvs/blog/local/lib/python2.7/site-packages/sass_processor/management/commands/compilescss.py", line 28, in handle
	    templates = self.find_templates()
	  File "~/apps/virtualenvs/blog/local/lib/python2.7/site-packages/sass_processor/management/commands/compilescss.py", line 39, in find_templates
	    for loader in self.get_loaders():
	  File "~/apps/virtualenvs/blog/local/lib/python2.7/site-packages/sass_processor/management/commands/compilescss.py", line 72, in get_loaders
	    for loader in template_source_loaders:
	TypeError: 'NoneType' object is not iterable

**Comment by drivard** [comment]
I tried against an empty project with only sass_processor app and still I am getting the error:
    django.template.base.TemplateDoesNotExist: test

Thanks

**Comment by drivard** [comment]
I'll make a fork and push some code, but to get it to pass, I had to modify the code in order to re-import the ``template_source_loaders``. I am not sure my code is exactly what it need to be but it has compiled my SCSS with success.

Plus I needed to add the following setting to get it to work ``COMPRESS_OFFLINE = True``

**Comment by jrief** [comment]
Thanks for this PR.
Parts of the code you see (and patched) here have been pilfered from **django-compressor**, therefore I am not familiar in detail with this code.
I unfortunately still am sticked on Django-1.6. Thanks for porting this it to 1.7.

**Comment by drivard** [comment]
resolved by #5

**Comment by drivard** [comment]
do you know when you will have time to upload the package to pypi?

**Comment by jrief** [comment]
I currently have the same problem, but running Django-1.6
If I have some more time, I'll dig into the code and try to fix it. Please use the version from GitHub, until it runs on Django-1.6 again.
