### ISSUE TITLE
ImportError: No module named django.conf in docker-compose

### ISSUE THREAD

**Issue by exos** [jrief/django-sass-processor#40]
Hi, I'm using docker-compose, and this is the secod time I build the container (the first works), If I try to install it in my local works, the problem is only when I build the container.

The error is:
```
▶ docker-compose build
db uses an image, skipping
Building web
Step 1 : FROM python:2.7
 ---> a047e3d0ae2b
Step 2 : ENV PYTHONUNBUFFERED 1
 ---> Using cache
 ---> 1185562aa2c3
Step 3 : RUN mkdir /code
 ---> Using cache
 ---> 9b6b22a35407
Step 4 : WORKDIR /code
 ---> Using cache
 ---> d57a69ce00c8
Step 5 : ADD requirements.txt /code/
 ---> Using cache
 ---> 391d56eb9d7e
Step 6 : RUN pip install -r requirements.txt
 ---> Running in 091eb695aaa0
Collecting Django==1.9.7 (from -r requirements.txt (line 1))
  Downloading Django-1.9.7-py2.py3-none-any.whl (6.6MB)
Collecting django-appconf==1.0.2 (from -r requirements.txt (line 2))
  Downloading django_appconf-1.0.2-py2.py3-none-any.whl
Collecting django-compressor==2.0 (from -r requirements.txt (line 3))
  Downloading django_compressor-2.0-py2.py3-none-any.whl (120kB)
Collecting django-friendly-tag-loader==1.2.1 (from -r requirements.txt (line 4))
  Downloading django_friendly_tag_loader-1.2.1-py2.py3-none-any.whl
Collecting django-sass-processor==0.4.0 (from -r requirements.txt (line 5))
  Downloading django-sass-processor-0.4.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-jJV1Sj/django-sass-processor/setup.py", line 6, in <module>
        from sass_processor import __version__
      File "/tmp/pip-build-jJV1Sj/django-sass-processor/sass_processor/__init__.py", line 25, in <module>
        from .processor import SassProcessor
      File "/tmp/pip-build-jJV1Sj/django-sass-processor/sass_processor/processor.py", line 6, in <module>
        from django.conf import settings
    ImportError: No module named django.conf
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-jJV1Sj/django-sass-processor/
ERROR: Service 'web' failed to build: The command '/bin/sh -c pip install -r requirements.txt' returned a non-zero code: 1
```

My Dockerfile: 

```
FROM python:2.7
ENV PYTHONUNBUFFERED 1
RUN mkdir /code
WORKDIR /code
ADD requirements.txt /code/
RUN pip install -r requirements.txt
ADD . /code/
```

And the docker-compose.yml:
``` 
version: '2'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "...."
      MYSQL_DATABASE: "Proyect"
      MYSQL_USER: "proyect"
      MYSQL_PASSWORD: "...."
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
```

Versions:

```
django-appconf==1.0.2
django-compressor==2.0
django-friendly-tag-loader==1.2.1
django-sass-processor==0.4.0
django-social-auth==0.7.28
djangorestframework==3.3.3
django-sass-processor==0.4.0
libsass==0.11.1
```

**Comment by ebpetway** [comment]
Confirmed. Cannot pip install as it is. The problem is in the __init__.py file, there's an import of the SassProcessor, which in turn tries to import from django settings, which don't even exist yet. I may submit a pull request later this week.

**Comment by rfleschenberg** [comment]
This seems relevant as current best practice documentation: https://packaging.python.org/single_source_version/

**Comment by jrief** [comment]
Please retry with 0.4.1 available from PyPI
