### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by benpetty** [jrief/django-sass-processor#92]
Not sure why, but all of the sudden we've started getting a SyntaxError when trying to run `./manage.py compilescss`

```
........................................................................................................................................Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/benny/foo_project/web-site/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/Users/benny/foo_project/web-site/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/benny/foo_project/web-site/env/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/benny/foo_project/web-site/env/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/Users/benny/foo_project/web-site/env/lib/python3.6/site-packages/sass_processor/management/commands/compilescss.py", line 153, in handle
    self.parse_source(py_source)
  File "/Users/benny/foo_project/web-site/env/lib/python3.6/site-packages/sass_processor/management/commands/compilescss.py", line 199, in parse_source
    tree = ast.parse(open(filename, 'rb').read())
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 5
    except Exception, e:
                    ^
SyntaxError: invalid syntax
```

Totally stumped as it was just working for weeks as of yesterday without any changes to the environment

settings.py
```
SASS_PROCESSOR_ENABLED = DEBUG
SASS_PROCESSOR_INCLUDE_DIRS = [
    os.path.join(STATIC_ROOT, 'scss'),
]
SASS_PROCESSOR_ROOT = STATIC_ROOT
SASS_PROCESSOR_AUTO_INCLUDE = False
SASS_PRECISION = 8
NODE_NPX_PATH = os.path.join(BASE_DIR, 'node_modules/npx')
```

pip freeze:
```
analytics-python==1.2.9
appnope==0.1.0
beautifulsoup4==4.6.0
boto3==1.4.8
botocore==1.8.6
certifi==2017.11.5
chardet==3.0.4
decorator==4.1.2
Django==1.11.7
-e git+https://github.com/airbrake/airbrake-django.git@02b0b422c6cdc8d5727bd6ea045bfdc362b380cd#egg=django_airbrake
django-appconf==1.0.2
django-classy-tags==0.8.0
django-compressor==2.2
django-crispy-forms==1.7.2
django-embed-video==1.1.2
django-htmlmin==0.10.0
django-modelcluster==3.1
django-sass-processor==0.7
django-sekizai==0.10.0
django-social-share==1.1.2
django-storages==1.6.5
django-taggit==0.22.1
django-treebeard==4.1.2
django-webpack-loader==0.6.0
djangorestframework==3.6.4
docutils==0.14
flake8==3.5.0
gunicorn==19.7.1
html5lib==0.999999999
idna==2.6
ipython==6.2.1
ipython-genutils==0.2.0
jedi==0.11.0
jmespath==0.9.3
libsass==0.14.5
lxml==4.2.1
mccabe==0.6.1
newrelic==2.98.0.81
olefile==0.44
parso==0.1.0
pexpect==4.3.0
pickleshare==0.7.4
Pillow==4.3.0
prompt-toolkit==1.0.15
psycopg2==2.7.3.2
ptyprocess==0.5.2
pycodestyle==2.3.1
pyflakes==1.6.0
Pygments==2.2.0
python-dateutil==2.6.1
pytz==2017.3
rcssmin==1.0.6
requests==2.18.4
rjsmin==1.0.12
s3transfer==0.1.12
simplegeneric==0.8.1
six==1.11.0
traitlets==4.3.2
Unidecode==0.4.21
urllib3==1.22
wagtail==1.13.1
wagtail-embed-videos==0.3.2
wagtailgeowidget==3.1.9
wcwidth==0.1.7
webencodings==0.5.1
Willow==1.0
```

Any help appreciated

**Comment by jrief** [comment]
From reading the stack trace, it seems as if you found a bug in Python's `ast` module itself. I almost can't believe that! Please recheck the Python sources, upgrade to 3.6.5 and if it's still there file a bug report for that AST module.

**Comment by benpetty** [comment]
Thanks @jrief, it seems that the bug was in the `django_airbrake` module. (https://github.com/airbrake/airbrake-django) Not sure exactly what exactly was causing it but removing that package fixed the problem.
